In [107]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [108]:
# Using the test_split funciton to split the dataset into training and testing datasets
from sklearn.model_selection import train_test_split # splits the dataset into traiing and testing sets
from sklearn.preprocessing import StandardScaler # standardizes the features by removing the mean and scaling them to unit variance
from sklearn.ensemble import RandomForestClassifier # a machine learning model that builds multiple decesion trees and merges them together to get a more accurate and stable prediciotn
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


In [109]:
# Loading the dataframe: 

df = pd.read_csv("heart-disease.csv")
df.shape

(303, 14)

In [110]:
# Preprocessing the data: 

X = df.drop('target', axis=1) # dropping the target variable from axis 1 and having X as Capital is a conveintion while y should be lowercase
# X is containing all the patient attributes or features except target
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [111]:
y = df['target'] # containing the target variable which has been dropped on X
# contaings the outcome we want to predict
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [112]:
# Splittng the data into 4 variables where
# X_train is a subset of X containing 80% of the data for training 
# X_test is a subset of X containing 20% of the data for testing
# y_train is a subset of y containing 80% of the data for training 
# y_test is a subset of y containing 20% of the data for testing 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=56)


In [113]:
f"""
X_Train: {X_train}
X_Test: {X_test}
y_Train: {y_train}
y_Test: {y_test}
"""

'\nX_Train:      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \\\n78    52    1   1       128   205    1        1      184      0      0.0   \n246   56    0   0       134   409    0        0      150      1      1.9   \n298   57    0   0       140   241    0        1      123      1      0.2   \n239   35    1   0       126   282    0        0      156      1      0.0   \n197   67    1   0       125   254    1        1      163      0      0.2   \n..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   \n233   64    1   0       120   246    0        0       96      1      2.2   \n142   42    0   2       120   209    0        1      173      0      0.0   \n122   41    0   2       112   268    0        0      172      1      0.0   \n235   51    1   0       140   299    0        1      173      1      1.6   \n192   54    1   0       120   188    0        1      113      0      1.4   \n\n     slope  ca  thal  \n78       2   0     2  \n246      1   

In [114]:
# Standardization: ensures that each feature contributes 

scaler = StandardScaler() # Standrdizes features by removing the mean and scaling to unit variance


scaler


StandardScaler()

In [115]:
X_train

# After standardization
print("Standardized the data: ")
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train
X_test

Standardized the data: 


array([[-1.07370947e+00,  7.15891053e-01, -1.18923150e-02,
        -1.90974993e-01,  1.16774761e+00, -4.11195970e-01,
        -1.07763181e+00,  8.75850166e-01, -6.83130051e-01,
        -8.58481617e-01,  9.71144252e-01, -7.08184816e-01,
        -5.08979293e-01],
       [ 9.54511885e-01,  7.15891053e-01, -9.71205729e-01,
        -8.02781109e-02,  1.64056097e-01, -4.11195970e-01,
        -1.07763181e+00, -1.27232555e-01, -6.83130051e-01,
         3.44386753e-01, -6.49662017e-01,  2.88214751e-01,
         1.11171793e+00],
       [ 8.41832921e-01,  7.15891053e-01, -1.18923150e-02,
        -1.90974993e-01, -6.90940378e-01,  2.43193045e+00,
        -1.07763181e+00, -4.32518601e-01, -6.83130051e-01,
        -8.58481617e-01,  9.71144252e-01, -7.08184816e-01,
        -5.08979293e-01],
       [ 1.06719085e+00,  7.15891053e-01, -9.71205729e-01,
         7.49948506e-01, -6.16592859e-01, -4.11195970e-01,
        -1.07763181e+00, -7.81416939e-01, -6.83130051e-01,
         8.59901769e-01, -6.49662017e

In [116]:
# Now we will train the model:
rf_model = RandomForestClassifier(n_estimators=5000, random_state=53)



In [117]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=5000, random_state=53)

In [118]:
rf_model

RandomForestClassifier(n_estimators=5000, random_state=53)

In [119]:
# now evaluate the model:

# Getting the prediction in y_pred

y_pred = rf_model.predict(X_test)

y_pred

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])

In [120]:
# confusion matrix which will compare the true labels y_test with the predicted labels (y_pred)

conf_matrix = confusion_matrix(y_test, y_pred)

conf_matrix

array([[22,  6],
       [ 7, 26]])

In [122]:
# classification report: generates a detailed report showing the performance metrics

class_report = classification_report(y_test, y_pred)

class_report

'              precision    recall  f1-score   support\n\n           0       0.76      0.79      0.77        28\n           1       0.81      0.79      0.80        33\n\n    accuracy                           0.79        61\n   macro avg       0.79      0.79      0.79        61\nweighted avg       0.79      0.79      0.79        61\n'

In [123]:
y_prob = rf_model.predict_proba(X_test)[:, 1]

In [124]:
y_prob

array([0.9192, 0.148 , 0.7736, 0.2134, 0.9722, 0.8922, 0.5158, 0.6992,
       0.9392, 0.481 , 0.4192, 0.9348, 0.52  , 0.076 , 0.0894, 0.4186,
       0.606 , 0.283 , 0.6332, 0.8344, 0.6944, 0.0932, 0.8376, 0.721 ,
       0.6752, 0.7146, 0.7916, 0.7268, 0.825 , 0.0618, 0.1444, 0.0038,
       0.8398, 0.0696, 0.8604, 0.9398, 0.7278, 0.002 , 0.0378, 0.0158,
       0.6032, 0.529 , 0.7714, 0.3248, 0.4434, 0.3866, 0.0182, 0.7986,
       0.2384, 0.343 , 0.923 , 0.1194, 0.9634, 0.0786, 0.9954, 0.0862,
       0.276 , 0.7448, 0.1886, 0.053 , 0.2202])